// sdk/src/adapters/svelte/components/Selections.svelte
<script lang="ts">
  /**
   * Selections container component for rendering all users' text selections
   * @module adapters/svelte/components/Selections
   */

  import Selection from './Selection.svelte'
  import type { SelectionUser } from '../types/selection'
  import type { CursorMode } from '../../../cursor/types'
  import type { Writable } from 'svelte/store'

  interface Props {
    /** Container store (required for container mode) */
    containerRef?: Writable<HTMLElement | null>
    /** Positioning mode (viewport or container) */
    mode?: CursorMode
    /** Selection box opacity (default: 0.2) */
    opacity?: number
    /** Users with selection data (from awareness) */
    users?: SelectionUser[]
  }

  let {
    containerRef = undefined,
    mode = 'viewport',
    opacity = 0.2,
    users = []
  }: Props = $props()

  // Filter users to only those with selections
  // Selection component handles deserialization and validation internally
  let usersWithSelections = $derived(
    users.filter(u => u.selection != null)
  )
</script>

{#each usersWithSelections as user (user.id)}
  <Selection
    {user}
    {mode}
    {containerRef}
    {opacity}
  />
{/each}

// sdk/src/adapters/vue/components/Selections.vue
<!--
  Selections container component for rendering all users' text selections
  @module adapters/vue/components/Selections
-->
<script setup lang="ts">
import { computed, type PropType, type Ref } from 'vue'
import Selection from './Selection.vue'
import type { SelectionUser } from '../types/selection'
import type { CursorMode } from '../../../cursor/types'

const props = defineProps({
  /** Document ID for awareness protocol */
  documentId: {
    type: String,
    required: true
  },
  /** Container element (required for container mode) */
  containerRef: {
    type: Object as PropType<Ref<HTMLElement | null> | null>,
    default: null
  },
  /** Positioning mode (viewport or container) */
  mode: {
    type: String as PropType<CursorMode>,
    default: 'viewport'
  },
  /** Show local user's selection (default: false) */
  showSelf: {
    type: Boolean,
    default: false
  },
  /** Selection box opacity (default: 0.2) */
  opacity: {
    type: Number,
    default: 0.2
  },
  /** Users with selection data (from awareness) */
  users: {
    type: Array as PropType<SelectionUser[]>,
    default: () => []
  }
})

// Filter users to only those with selections
// Selection component handles deserialization and validation internally
const usersWithSelections = computed(() =>
  props.users.filter(u => u.selection != null)
)
</script>

<template>
  <Selection
    v-for="user in usersWithSelections"
    :key="user.id"
    :user="user"
    :mode="mode"
    :container-ref="containerRef"
    :opacity="opacity"
  />
</template>
